# Generated by Django 3.2.12 on 2022-03-09 09:41

from django.db import migrations, models
import django.db.models.deletion
import game.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=1000, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=5, validators=[game.validators.question_point_validator], verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=2000, null=True, verbose_name='Question'),
        ),
    ]
