name: Create envfile

on: [ push ]

jobs:

  create-envfile:

    runs-on: self-hosted

    steps:
    - name: Make envfile
      run: |
        touch question_game/.env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
        echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
        echo DATABASE_PASS=${{ secrets.DATABASE_PASS }} >> .env
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
        cat question_game/.env