name: StDev CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    environment: production
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install venv
      run: virtualenv venv
    - name: Install Dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make envfile
      run: |
        touch question_game/.env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> question_game/.env
        echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> question_game/.env
        echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> question_game/.env
        echo DATABASE_PASS=${{ secrets.DATABASE_PASS }} >> question_game/.env
        echo DEBUG=${{ secrets.DEBUG }} >> question_game/.env
        echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> question_game/.env
        cat question_game/.env
    - name: Migrate changes
      run: |
        source venv/bin/activate
        python manage.py migrate
    - name: Collect static
      run: | 
        source venv/bin/activate
        python manage.py collectstatic
    - name: Restart ctls
      run: |
        systemctl restart stdev_gunicorn
